// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfnaLaY7Tip7FKkXXnsXN6tvAjQxOIVdc',
    appId: '1:187752097311:web:d2fa250395591592de172a',
    messagingSenderId: '187752097311',
    projectId: 'track-app-2026',
    authDomain: 'track-app-2026.firebaseapp.com',
    storageBucket: 'track-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDafwQ0MZ5p3uPS6cWDznjDlpTSpu95jA0',
    appId: '1:187752097311:android:7a6c75a15d7be470de172a',
    messagingSenderId: '187752097311',
    projectId: 'track-app-2026',
    storageBucket: 'track-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFyGoxAOnQy3-ugx4KtxhZsbnF_8_PFU',
    appId: '1:187752097311:ios:b8229ba32e007ff6de172a',
    messagingSenderId: '187752097311',
    projectId: 'track-app-2026',
    storageBucket: 'track-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoFyGoxAOnQy3-ugx4KtxhZsbnF_8_PFU',
    appId: '1:187752097311:ios:b8229ba32e007ff6de172a',
    messagingSenderId: '187752097311',
    projectId: 'track-app-2026',
    storageBucket: 'track-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfnaLaY7Tip7FKkXXnsXN6tvAjQxOIVdc',
    appId: '1:187752097311:web:7d2665845ebe3f33de172a',
    messagingSenderId: '187752097311',
    projectId: 'track-app-2026',
    authDomain: 'track-app-2026.firebaseapp.com',
    storageBucket: 'track-app-2026.firebasestorage.app',
  );
}
